invitees = ['Phil', 'Yuri', 'Rome', 'Nick']
print(f"Let's go to dinner, {invitees[0]}!")
print(f"Let's go to dinner, {invitees[1]}!")
print(f"Let's go to dinner, {invitees[2]}!")
print(f"Let's go to dinner, {invitees[3]}!")
print(f"Oh no! {invitees[3]} can't make it! Let's invite someone else.")
invitees.pop(3)
invitees.insert(3, 'Vlad')
print(f"Let's go to dinner, {invitees[0]}!")
print(f"Let's go to dinner, {invitees[1]}!")
print(f"Let's go to dinner, {invitees[2]}!")
print(f"Let's go to dinner, {invitees[3]}!")
print(f"Oh, we've found a bigger table! Let's invite some more people!")
invitees.insert(0, 'Andrew')
invitees.insert(3, 'Jerome')
invitees.append('Lapsha')
print(f"Let's go to dinner, {invitees[0]}!")
print(f"Let's go to dinner, {invitees[1]}!")
print(f"Let's go to dinner, {invitees[2]}!")
print(f"Let's go to dinner, {invitees[3]}!")
print(f"Let's go to dinner, {invitees[4]}!")
print(f"Let's go to dinner, {invitees[5]}!")
print(f"Let's go to dinner, {invitees[6]}!")
print(f"Crap, the table won't arrive on time! We gotta kick people out.")
invitees.pop()
invitees.pop()
invitees.pop()
invitees.pop()
invitees.pop()
print(f"You're still invited, {invitees[0]} and {invitees[1]}!")
del invitees[0]
del invitees[0]
print(f"I have invited {invitees}")